# Generated by Django 3.2.6 on 2023-08-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookstore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('idx', models.PositiveSmallIntegerField()),
                ('total_seconds', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female'), (2, 'Trans')], default=0, null=True)),
            ],
        ),
    ]
