# Generated by Django 3.2.6 on 2023-08-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstores', '0002_auto_20230804_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(blank=True, to='bookstores.Category'),
        ),
    ]
